config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('st_martins.core_web.urls')),
    path('portal/', include('st_martins.pores_portal.urls')),
    path('school_media/', include('st_martins.school_media.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

st_martins/core_web/urls.py
from django.urls import path

from . import views


app_name = 'core_web'

urlpatterns = [
    path('', views.index, name='index'),
    path("contact/", views.contactView, name="contact"),
    path("success", views.successView, name="success"),
]

st_martins/school_media/urls.py
from django.urls import path

from . import views


app_name = 'school_media'

urlpatterns = [
    path("", views.galleryView, name="gallery"),
    path("videos", views.videoView, name="videos"),
    path("add_video", views.addVideo, name="add_video"),
    path("add_photo", views.addPhoto, name="add_photo"),
]

st_martins/school_media/models.py
from django.utils import timezone
from cloudinary_storage.storage import VideoMediaCloudinaryStorage, MediaCloudinaryStorage
# from cloudinary_storage.validators import validate_video
from django.db import models
from cloudinary.models import CloudinaryField


# Create your models here.
class photos(models.Model):
    title = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to='images/', blank=True, storage=MediaCloudinaryStorage(), )
    description = models.TextField(max_length=500, blank=True)


class Videos(models.Model):
    title = models.CharField(max_length=200, blank=True)
    video = models.FileField(upload_to='videos/', blank=True, storage=VideoMediaCloudinaryStorage())
    description = models.TextField(max_length=500, blank=True)
    date = models.DateTimeField(auto_now_add=True)

st_martins/school_media/forms.py
from cloudinary.forms import CloudinaryFileField
from django.forms import ModelForm
from .models import *


class VideoForm(ModelForm):
    class Meta:
        model = Videos
        fields = "__all__"

        video = CloudinaryFileField(
            options={
                'tags': "directly_uploaded",
                'crop': 'limit', 'width': 1000, 'height': 1000,
                'eager': [{'crop': 'fill', 'width': 150, 'height': 100}]
            })


class PhotoForm(ModelForm):
    class Meta:
        model = photos
        fields = "__all__"

        image = CloudinaryFileField(
            options={
                'tags': "directly_uploaded",
                'crop': 'limit', 'width': 1000, 'height': 1000,
                'eager': [{'crop': 'fill', 'width': 150, 'height': 100}]
            })

st_martins/school_media/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from cloudinary.forms import cl_init_js_callbacks

from .models import *
from .forms import VideoForm, PhotoForm


# Create your views here.
def galleryView(request):
    photo = photos.objects.all()

    ctx = {'photo': photo}

    return render(request, 'school_media/gallery.html', ctx)


def videoView(request):
    video = Videos.objects.all()

    ctx = {'video': video}

    return render(request, 'school_media/videos.html', ctx)


def addVideo(request):
    context = dict(backend_form=VideoForm())

    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        context['posted'] = form.instance
        if form.is_valid():
            video = form.save(commit=False)
            video.user = request.user
            video.save()
            return redirect('videoView')
    else:
        form = VideoForm()
    return render(request, 'school_media/videos.html', context)

def addPhoto(request):
    context = dict(backend_form=PhotoForm())

    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        context['posted'] = form.instance
        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user
            photo.save()
            return redirect('galleryView')
    else:
        form = PhotoForm()
    return render(request, 'school_media/gallery.html', context)

st_martins/school_media/templates/school_media/addVideo.html
{% extends 'base.html' %}
{% load cloudinary %}
{% load static %}

{% block body %}
  <div id='backend_upload'>
    <form action="{% url 'school_media:add_video' %}" method="post"
          enctype="multipart/form-data">
      {% csrf_token %}
      {{ backend_form }}
      <input type="submit" value="Upload">
    </form>
  </div>
{% endblock %}

st_martins/school_media/templates/school_media/gallery.html
{% extends 'base.html' %}

{% load static %}
{% load cloudinary %}
{% load cloudinary_static %}


{% block content %}
<!-- Photo Grid -->
<div class="row" style="border-radius:3px;">
  {% for pic in photo %}
  <div class="column">
    <h2 style="color:white">{{pic.title}}</h2>
            <img src="{{pic.image.url}}" alt="{{pic.image.description}}">
            <h6 style="color:white">{{pic.description}}</h6>
  </div>
  {% endfor %}
  <div class="column">
    <img src="{% static 'images/betty.jpeg' %}" width="90%" alt="">
      <img src="https://res.cloudinary.com/dlcvinuok/image/upload/v1673372207/cld-sample-3.jpg" alt="" width="60%">
</div>
</div>
{% include "footer.html" %}
{% endblock %}

st_martins/school_media/templates/school_media/side_bar.html
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link type="text/css" rel="stylesheet" href="{% static 'css/side_bar.css' %}"/>
<script src="{% static 'js/side_bar.js' %}"></script>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

  <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
        <a href="{% url 'core_web:index' %}">St Martins School</a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <div class="sidebar-header">
        <div class="user-pic">
          <img class="img-responsive img-rounded" src="{% static 'images/logo.png' %}"
            alt="User picture">
        </div>
        <div class="user-info">
          <span class="user-name">
            <strong>{{user.user.name}}</strong>
          </span>
          <span class="user-role">Administrator</span>
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
        </div>
      </div>
      <!-- sidebar-header  -->
      <div class="sidebar-search">
        <div>
          <div class="input-group">
            <input type="text" class="form-control search-menu" placeholder="search">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      <!-- sidebar-search  -->
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span>Home</span>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-tachometer-alt"></i>
              <span>Dashboard</span>
              <span class="badge badge-pill badge-warning">New</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Grade 1
                    <span class="badge badge-pill badge-success">Top</span>
                  </a>
                </li>
                <li>
                  <a href="#">Grade 2</a>
                </li>
                <li>
                  <a href="#">Grade 3</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa-solid fa-e"></i>
              <span>E-Learning</span>
              <span class="badge badge-pill badge-danger">2</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">i-Classes

                  </a>
                </li>
                <li>
                  <a href="#">Quizzes</a>
                </li>
                <li>
                  <a href="#">Tutorials</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa-solid fa-l"></i>
              <span>Learning Materials</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">General</a>
                </li>
                <li>
                  <a href="#">Exams</a>
                </li>
                <li>
                  <a href="#">Tables</a>
                </li>
                <li>
                  <a href="#">Crafts</a>
                </li>
                <li>
                  <a href="#">Forms</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-chart-line"></i>
              <span>Charts</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Pie chart</a>
                </li>
                <li>
                  <a href="#">Line chart</a>
                </li>
                <li>
                  <a href="#">Bar chart</a>
                </li>
                <li>
                  <a href="#">Histogram</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="sidebar-dropdown">
            <a href="#">
              <i class="fa fa-globe"></i>
              <span>Paths</span>
            </a>
            <div class="sidebar-submenu">
              <ul>
                <li>
                  <a href="#">Technology</a>
                </li>
                <li>
                  <a href="#">Art & Music</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="header-menu">
            <span>Extra</span>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-book"></i>
              <span>E-Library</span>
              <span class="badge badge-pill badge-primary">Beta</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-calendar"></i>
              <span>Calendar</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa-brands fa-youtube"></i>
              <span>Tutorial Examples</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
      <a href="#">
        <i class="fa fa-bell"></i>
        <span class="badge badge-pill badge-warning notification">3</span>
      </a>
      <a href="#">
        <i class="fa fa-envelope"></i>
        <span class="badge badge-pill badge-success notification">7</span>
      </a>
      <a href="#">
        <i class="fa fa-cog"></i>
        <span class="badge-sonar"></span>
      </a>
      <a href="#">
        <i class="fa fa-power-off"></i>
      </a>
    </div>
  </nav>

  <!-- sidebar-wrapper  -->
  <!-- page-content" -->

<!-- page-wrapper -->

st_martins/school_media/templates/school_media/video_card.html
<script>
  @media only screen and (min-width: 768px) {
  iframe{
    height: 13em;
  }
  .card{
    width: 30%;
  }
  video {
  opacity: 0.5;
}
</script>
<section class="">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
<div class="embed-responsive embed-responsive-16by9">
  <iframe src="https://www.youtube.com/embed/pWahNIMRxR0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card
      title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
    </div>
<div class="card bg-dark text-white">
  <video src="video.mp4" autoplay loop></video>
  <div class="card-img-overlay">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text">Last updated 3 mins ago</p>
  </div>
</div>
      </div>
    </div>
  </div>

</section>

st_martins/school_media/templates/school_media/videos.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}
{% load cloudinary_static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/videos.css' %}"/>

<div class="page-wrapper chiller-theme toggled">
{% include 'school_media/side_bar.html' %}
 <main class="page-content">
    <div class="container-fluid">
      <h2>Learner's Hub</h2>
      <hr>
      <div class="row">
        <div class="grid-container grid-container--fit">
          {% for file in video %}
          <div class="grid-element">
           <video controls>
              <source src="{{file.video.url}}" crop="fill" class="card-img-top rounded-0" type="video/mp4">
            </video>
          <small>{{file.description}}</small>
            <small href="" class="btn btn-dark btn-sm">🔥</small>
            <small href="" class="btn btn-dark btn-sm">👍</small>
            </div>
            {% endfor %}
          </div>


        </div>
      <strong><h3>   More Tutorials</h3></strong>
      <hr>
      <div class="row">
        {% for file in video %}

        <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4">
          <div class="card rounded-1 p-0 shadow-sm">
            <a>
              <video width="320" height="230" controls>
              <source src="{{file.video.url}}" crop="fill" class="card-img-top rounded-0" type="video/mp4">
            </video>
            </a>
            <div class="card-body text-left">
              <h6 class="card-title">{{file.title}}</h6>

               <p style="color:white">{{file.description}}</p>

            </div>
          </div>
        </div>
        {% endfor %}

        <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4">
          <div class="card rounded-0 p-0 shadow-sm">
            <img src="https://res.cloudinary.com/dlcvinuok/image/upload/v1676039703/media/images/ral4e1axrgxhyppvk4m9.jpg" class="card-img-top rounded-0" alt="Angular pro sidebar">
            <div class="card-body text-center">
              <h6 class="card-title">St Martins school gallery</h6>
              <a href="" target="" class="btn btn-primary btn-sm">👍</a>
              <a href="" target="" class="btn btn-success btn-sm">More</a>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4">
          <div class="card rounded-0 p-0 shadow-sm">
            <img src="https://res.cloudinary.com/dlcvinuok/image/upload/v1676039657/media/images/utejbpqkls4no5f0n9pm.jpg" class="card-img-top rounded-0" alt="St Martins school">
            <div class="card-body text-center">
              <h6 class="card-title">St Martins culture and activities</h6>
              <a href="" target="" class="btn btn-primary btn-sm">🔥</a>
              <a href="" target="" class="btn btn-success btn-sm">More</a>
            </div>
          </div>
        </div>
      </div>
      <hr>
    </div>
</main>

{% endblock %}
<script src="{% static 'js/bootstrap-toggle.js' %}"></script>