config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('st_martins.core_web.urls')),
    path('portal/', include('st_martins.pores_portal.urls')),
    path('school_media/', include('st_martins.school_media.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

st_martins/core_web/urls.py
from django.urls import path

from . import views


app_name = 'core_web'

urlpatterns = [
    path('', views.index, name='index'),
    path("contact/", views.contactView, name="contact"),
    path("success", views.successView, name="success"),
]

st_martins/pores_portal/urls.py
from django.urls import path, include
from . import views
from . import hod_views, staff_views, student_views

app_name = 'pores_portal'

urlpatterns = [
    path('', views.loginPage, name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', hod_views.admin_home, name="admin_home"),
    path('add_staff/', hod_views.add_staff, name="add_staff"),
    path('add_staff_save/', hod_views.add_staff_save, name="add_staff_save"),
    path('manage_staff/', hod_views.manage_staff, name="manage_staff"),
    path('edit_staff/<staff_id>/', hod_views.edit_staff, name="edit_staff"),
    path('edit_staff_save/', hod_views.edit_staff_save, name="edit_staff_save"),
    path('delete_staff/<staff_id>/', hod_views.delete_staff, name="delete_staff"),
    path('add_course/', hod_views.add_course, name="add_course"),
    path('add_course_save/', hod_views.add_course_save, name="add_course_save"),
    path('manage_course/', hod_views.manage_course, name="manage_course"),
    path('edit_course/<course_id>/', hod_views.edit_course, name="edit_course"),
    path('edit_course_save/', hod_views.edit_course_save, name="edit_course_save"),
    path('delete_course/<course_id>/', hod_views.delete_course, name="delete_course"),
    path('manage_session/', hod_views.manage_session, name="manage_session"),
    path('add_session/', hod_views.add_session, name="add_session"),
    path('add_session_save/', hod_views.add_session_save, name="add_session_save"),
    path('edit_session/<session_id>', hod_views.edit_session, name="edit_session"),
    path('edit_session_save/', hod_views.edit_session_save, name="edit_session_save"),
    path('delete_session/<session_id>/', hod_views.delete_session, name="delete_session"),
    path('add_student/', hod_views.add_student, name="add_student"),
    path('add_student_save/', hod_views.add_student_save, name="add_student_save"),
    path('edit_student/<student_id>', hod_views.edit_student, name="edit_student"),
    path('edit_student_save/', hod_views.edit_student_save, name="edit_student_save"),
    path('manage_student/', hod_views.manage_student, name="manage_student"),
    path('delete_student/<student_id>/', hod_views.delete_student, name="delete_student"),
    path('add_subject/', hod_views.add_subject, name="add_subject"),
    path('add_subject_save/', hod_views.add_subject_save, name="add_subject_save"),
    path('manage_subject/', hod_views.manage_subject, name="manage_subject"),
    path('edit_subject/<subject_id>/', hod_views.edit_subject, name="edit_subject"),
    path('edit_subject_save/', hod_views.edit_subject_save, name="edit_subject_save"),
    path('delete_subject/<subject_id>/', hod_views.delete_subject, name="delete_subject"),
    path('check_email_exist/', hod_views.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', hod_views.check_username_exist, name="check_username_exist"),
    path('student_feedback_message/', hod_views.student_feedback_message, name="student_feedback_message"),
    path('student_feedback_message_reply/', hod_views.student_feedback_message_reply,
         name="student_feedback_message_reply"),
    path('staff_feedback_message/', hod_views.staff_feedback_message, name="staff_feedback_message"),
    path('staff_feedback_message_reply/', hod_views.staff_feedback_message_reply, name="staff_feedback_message_reply"),
    path('student_leave_view/', hod_views.student_leave_view, name="student_leave_view"),
    path('student_leave_approve/<leave_id>/', hod_views.student_leave_approve, name="student_leave_approve"),
    path('student_leave_reject/<leave_id>/', hod_views.student_leave_reject, name="student_leave_reject"),
    path('staff_leave_view/', hod_views.staff_leave_view, name="staff_leave_view"),
    path('staff_leave_approve/<leave_id>/', hod_views.staff_leave_approve, name="staff_leave_approve"),
    path('staff_leave_reject/<leave_id>/', hod_views.staff_leave_reject, name="staff_leave_reject"),
    path('admin_view_attendance/', hod_views.admin_view_attendance, name="admin_view_attendance"),
    path('admin_get_attendance_dates/', hod_views.admin_get_attendance_dates, name="admin_get_attendance_dates"),
    path('admin_get_attendance_student/', hod_views.admin_get_attendance_student, name="admin_get_attendance_student"),
    path('admin_profile/', hod_views.admin_profile, name="admin_profile"),
    path('admin_profile_update/', hod_views.admin_profile_update, name="admin_profile_update"),

    # URLS for Staff
    path('staff_home/', staff_views.staff_home, name="staff_home"),
    path('staff_take_attendance/', staff_views.staff_take_attendance, name="staff_take_attendance"),
    path('get_students/', staff_views.get_students, name="get_students"),
    path('save_attendance_data/', staff_views.save_attendance_data, name="save_attendance_data"),
    path('staff_update_attendance/', staff_views.staff_update_attendance, name="staff_update_attendance"),
    path('get_attendance_dates/', staff_views.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_student/', staff_views.get_attendance_student, name="get_attendance_student"),
    path('update_attendance_data/', staff_views.update_attendance_data, name="update_attendance_data"),
    path('staff_apply_leave/', staff_views.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save/', staff_views.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback/', staff_views.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save/', staff_views.staff_feedback_save, name="staff_feedback_save"),
    path('staff_profile/', staff_views.staff_profile, name="staff_profile"),
    path('staff_profile_update/', staff_views.staff_profile_update, name="staff_profile_update"),
    path('staff_add_result/', staff_views.staff_add_result, name="staff_add_result"),
    path('staff_add_result_save/', staff_views.staff_add_result_save, name="staff_add_result_save"),

    # URSL for Student
    path('student_home/', student_views.student_home, name="student_home"),
    path('student_view_attendance/', student_views.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', student_views.student_view_attendance_post,
         name="student_view_attendance_post"),
    path('student_apply_leave/', student_views.student_apply_leave, name="student_apply_leave"),
    path('student_apply_leave_save/', student_views.student_apply_leave_save, name="student_apply_leave_save"),
    path('student_feedback/', student_views.student_feedback, name="student_feedback"),
    path('student_feedback_save/', student_views.student_feedback_save, name="student_feedback_save"),
    path('student_profile/', student_views.student_profile, name="student_profile"),
    path('student_profile_update/', student_views.student_profile_update, name="student_profile_update"),
    path('student_view_result/', student_views.student_view_result, name="student_view_result"),
]

st_martins/school_media/urls.py
from django.urls import path

from . import views


app_name = 'school_media'

urlpatterns = [
    path("", views.galleryView, name="gallery"),
    path("videos", views.videoView, name="videos"),
    path("add_video", views.addVideo, name="add_video"),
    path("add_photo", views.addPhoto, name="add_photo"),
]

st_martins/core_web/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class CustomUser(AbstractUser):
    user_type_data = ((1, "HOD"), (2, "Staff"), (3, "Student"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)

class Contact(models.Model):
    name = models.CharField(max_length=254, null=True, blank=True)
    email = models.EmailField(blank=False, null=True)
    message = models.TextField(blank=False, null=True)

    def __str__(self):
        return self.name

st_martins/school_media/models.py
from django.utils import timezone
from cloudinary_storage.storage import VideoMediaCloudinaryStorage, MediaCloudinaryStorage
# from cloudinary_storage.validators import validate_video
from django.db import models
from cloudinary.models import CloudinaryField


# Create your models here.
class photos(models.Model):
    title = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to='images/', blank=True, storage=MediaCloudinaryStorage(), )
    description = models.TextField(max_length=500, blank=True)


class Videos(models.Model):
    title = models.CharField(max_length=200, blank=True)
    video = models.FileField(upload_to='videos/', blank=True, storage=VideoMediaCloudinaryStorage())
    description = models.TextField(max_length=500, blank=True)
    date = models.DateTimeField(auto_now_add=True)

st_martins/core_web/forms.py
from django import forms
from django.conf import settings


class ContactForm(forms.Form):
    template_name = 'contact_form.html'

    sender = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(required=True)

st_martins/school_media/forms.py
from cloudinary.forms import CloudinaryFileField
from django.forms import ModelForm
from .models import *


class VideoForm(ModelForm):
    class Meta:
        model = Videos
        fields = "__all__"

        video = CloudinaryFileField(
            options={
                'tags': "directly_uploaded",
                'crop': 'limit', 'width': 1000, 'height': 1000,
                'eager': [{'crop': 'fill', 'width': 150, 'height': 100}]
            })


class PhotoForm(ModelForm):
    class Meta:
        model = photos
        fields = "__all__"

        image = CloudinaryFileField(
            options={
                'tags': "directly_uploaded",
                'crop': 'limit', 'width': 1000, 'height': 1000,
                'eager': [{'crop': 'fill', 'width': 150, 'height': 100}]
            })

st_martins/core_web/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm
from .models import Contact


def index(request):
    return render(request, "core_web/index.html", locals())


def contactView(request):
    if request.method == "POST":
        contact = Contact()
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        contact.name = name
        contact.email = email
        contact.message = message
        contact.save()

    return render(request, 'core_web/contact_form.html')


def successView(request):
    return HttpResponse("Success! Thank you for contacting us, we will get back to you as soon as possible.")

st_martins/pores_portal/views.py
# from channels.auth import login, logout
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages

from .email_backend import EmailBackEnd


def home(request):
    return render(request, 'pores_portal/index.html')


def loginPage(request):
    return render(request, 'pores_portal/login.html')


def doLogin(request):
    if request.method != "POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        user = EmailBackEnd.authenticate(request, username=request.POST.get('email'),
                                         password=request.POST.get('password'))
        if user != None:
            login(request, user)
            user_type = user.user_type
            # return HttpResponse("Email: "+request.POST.get('email')+ " Password: "+request.POST.get('password'))
            if user_type == '1':
                return redirect('pores_portal:admin_home')

            elif user_type == '2':
                # return HttpResponse("Staff Login")
                return redirect('pores_portal:staff_home')

            elif user_type == '3':
                # return HttpResponse("Student Login")
                return redirect('pores_portal:student_home')
            else:
                messages.error(request, "Invalid Login!")
                return redirect('login')
        else:
            messages.error(request, "Invalid Login Credentials!")
            # return HttpResponseRedirect("/")
            return redirect('login')


def get_user_details(request):
    if request.user != None:
        return HttpResponse("User: " + request.user.email + " User Type: " + request.user.user_type)
    else:
        return HttpResponse("Please Login First")


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')

st_martins/school_media/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from cloudinary.forms import cl_init_js_callbacks

from .models import *
from .forms import VideoForm, PhotoForm


# Create your views here.
def galleryView(request):
    photo = photos.objects.all()

    ctx = {'photo': photo}

    return render(request, 'school_media/gallery.html', ctx)


def videoView(request):
    video = Videos.objects.all()

    ctx = {'video': video}

    return render(request, 'school_media/videos.html', ctx)


def addVideo(request):
    context = dict(backend_form=VideoForm())

    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        context['posted'] = form.instance
        if form.is_valid():
            video = form.save(commit=False)
            video.user = request.user
            video.save()
            return redirect('videoView')
    else:
        form = VideoForm()
    return render(request, 'school_media/videos.html', context)

def addPhoto(request):
    context = dict(backend_form=PhotoForm())

    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        context['posted'] = form.instance
        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user
            photo.save()
            return redirect('galleryView')
    else:
        form = PhotoForm()
    return render(request, 'school_media/gallery.html', context)

st_martins/templates/base.html
{% load static %}
{% load cloudinary %}
{% load cloudinary_static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="description" content="St Martins Depores official website" />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href=" {% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href=" {% static 'owlcarousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href=" {% static 'owlcarousel/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/donation.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/gallery.css' %}" />

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <!-- CSS File -->



    <!-- Font Awesome 5.15.1 CSS -->
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css'>
    <title>{% block title %}St Martins DP School{% endblock %}</title>
</head>


<body>
<div class="logo">
    <a><img class="logo img" style="width:60%; height:60%; max-width:75px;" src ="{% static 'images/trace.svg' %}" width="60"></a>
     <a class="navbar-brand jina" href="{% url 'core_web:index' %}">
         <span>ST MARTINS</span> DP SCHOOL
     </a>


</div>
{% include "navbar.html" %}

    <div data-bs-spy="scroll" data-bs-target="#navbar-scroll-boo" data-bs-offset="0" class="scrollspy-example"
        tabindex="0">
        {% block content %}

        {% endblock %}

</div>

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/donation.js' %}"></script>
    <script src="{% static 'js/js.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

st_martins/templates/footer.html
<footer>
        <p>
            <i class="fa fa-copyright"></i> COPYRIGHT <span id="date"></span> St Martins School Build by <a
                href="#" target="_blank">St Martins Team</a>
        </p>
    <div class="wrapper">
  <a href="#" class="icon facebook">
    <div class="tooltip">Facebook</div>
    <span><i class="fab fa-facebook-f"></i></span>
  </a>
  <a href="https://twitter.com/stmartinschool_?s=11&t=VF5kKJBmkO2KyV-c4Nv-xg" class="icon twitter" target="_blank">
    <div class="tooltip">Twitter</div>
    <span><i class="fab fa-twitter"></i></span>
  </a>
  <a href="https://instagram.com/st_martin_school?igshid=YmMyMTA2M2Y=" class="icon instagram" target="_blank">
    <div class="tooltip">Instagram</div>
    <span><i class="fab fa-instagram"></i></span>
  </a>
  <a href="#" class="icon youtube">
    <div class="tooltip">Youtube</div>
    <span><i class="fab fa-youtube"></i></span>
  </a>
</div>
</footer>

st_martins/templates/navbar.html
{% load static %}

 <nav id="navbar-scroll-boo" class="autohide navbar navbar-expand-lg navbar-dark nav-color text-uppercase">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse navbar-position" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item list-style">
                            <a class="nav-link active" aria-current="page" href= "{% url 'core_web:index' %}">Home</a>
                        </li>
                        <li class="nav-item dropdown list-style">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                About us
                            </a>
                            <ul class="dropdown-menu nav-color" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item dropdown-style" href="#whoWeAre">who we are?</a></li>
                                <li><a class="dropdown-item dropdown-style" href="#whatWeDo">what we do?</a></li>
                                <li><a class="dropdown-item dropdown-style" href="#howItWork">our Activities</a></li>
                                <li><a class="dropdown-item dropdown-style" href="#">external url</a></li>
                            </ul>
                        </li>
                        <li class="nav-item list-style">
                            <a class="nav-link" href="{% url 'school_media:gallery' %}">Gallery</a>
                        </li>
                          <li class="nav-item list-style">
                            <a class="nav-link" href="{% url 'school_media:videos' %}">Leaner's Hub</a>
                        </li>
                        <li class="nav-item list-style">
                            <a class="nav-link" href="{% url 'core_web:contact' %}">Contact Us</a>
                        </li>
                        <li class="nav-item list-style">
                            <a class="nav-link" href="{% url 'pores_portal:login' %}">Log in</a>
                        </li>

                    </ul>
                </div>
            </div>

        </nav>