config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('st_martins.core_web.urls')),
    path('portal/', include('st_martins.pores_portal.urls')),
    path('school_media/', include('st_martins.school_media.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

st_martins/pores_portal/urls.py
from django.urls import path, include
from . import views
from . import hod_views, staff_views, student_views

app_name = 'pores_portal'

urlpatterns = [
    path('', views.loginPage, name="login"),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('get_user_details/', views.get_user_details, name="get_user_details"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('admin_home/', hod_views.admin_home, name="admin_home"),
    path('add_staff/', hod_views.add_staff, name="add_staff"),
    path('add_staff_save/', hod_views.add_staff_save, name="add_staff_save"),
    path('manage_staff/', hod_views.manage_staff, name="manage_staff"),
    path('edit_staff/<staff_id>/', hod_views.edit_staff, name="edit_staff"),
    path('edit_staff_save/', hod_views.edit_staff_save, name="edit_staff_save"),
    path('delete_staff/<staff_id>/', hod_views.delete_staff, name="delete_staff"),
    path('add_course/', hod_views.add_course, name="add_course"),
    path('add_course_save/', hod_views.add_course_save, name="add_course_save"),
    path('manage_course/', hod_views.manage_course, name="manage_course"),
    path('edit_course/<course_id>/', hod_views.edit_course, name="edit_course"),
    path('edit_course_save/', hod_views.edit_course_save, name="edit_course_save"),
    path('delete_course/<course_id>/', hod_views.delete_course, name="delete_course"),
    path('manage_session/', hod_views.manage_session, name="manage_session"),
    path('add_session/', hod_views.add_session, name="add_session"),
    path('add_session_save/', hod_views.add_session_save, name="add_session_save"),
    path('edit_session/<session_id>', hod_views.edit_session, name="edit_session"),
    path('edit_session_save/', hod_views.edit_session_save, name="edit_session_save"),
    path('delete_session/<session_id>/', hod_views.delete_session, name="delete_session"),
    path('add_student/', hod_views.add_student, name="add_student"),
    path('add_student_save/', hod_views.add_student_save, name="add_student_save"),
    path('edit_student/<student_id>', hod_views.edit_student, name="edit_student"),
    path('edit_student_save/', hod_views.edit_student_save, name="edit_student_save"),
    path('manage_student/', hod_views.manage_student, name="manage_student"),
    path('delete_student/<student_id>/', hod_views.delete_student, name="delete_student"),
    path('add_subject/', hod_views.add_subject, name="add_subject"),
    path('add_subject_save/', hod_views.add_subject_save, name="add_subject_save"),
    path('manage_subject/', hod_views.manage_subject, name="manage_subject"),
    path('edit_subject/<subject_id>/', hod_views.edit_subject, name="edit_subject"),
    path('edit_subject_save/', hod_views.edit_subject_save, name="edit_subject_save"),
    path('delete_subject/<subject_id>/', hod_views.delete_subject, name="delete_subject"),
    path('check_email_exist/', hod_views.check_email_exist, name="check_email_exist"),
    path('check_username_exist/', hod_views.check_username_exist, name="check_username_exist"),
    path('student_feedback_message/', hod_views.student_feedback_message, name="student_feedback_message"),
    path('student_feedback_message_reply/', hod_views.student_feedback_message_reply,
         name="student_feedback_message_reply"),
    path('staff_feedback_message/', hod_views.staff_feedback_message, name="staff_feedback_message"),
    path('staff_feedback_message_reply/', hod_views.staff_feedback_message_reply, name="staff_feedback_message_reply"),
    path('student_leave_view/', hod_views.student_leave_view, name="student_leave_view"),
    path('student_leave_approve/<leave_id>/', hod_views.student_leave_approve, name="student_leave_approve"),
    path('student_leave_reject/<leave_id>/', hod_views.student_leave_reject, name="student_leave_reject"),
    path('staff_leave_view/', hod_views.staff_leave_view, name="staff_leave_view"),
    path('staff_leave_approve/<leave_id>/', hod_views.staff_leave_approve, name="staff_leave_approve"),
    path('staff_leave_reject/<leave_id>/', hod_views.staff_leave_reject, name="staff_leave_reject"),
    path('admin_view_attendance/', hod_views.admin_view_attendance, name="admin_view_attendance"),
    path('admin_get_attendance_dates/', hod_views.admin_get_attendance_dates, name="admin_get_attendance_dates"),
    path('admin_get_attendance_student/', hod_views.admin_get_attendance_student, name="admin_get_attendance_student"),
    path('admin_profile/', hod_views.admin_profile, name="admin_profile"),
    path('admin_profile_update/', hod_views.admin_profile_update, name="admin_profile_update"),

    # URLS for Staff
    path('staff_home/', staff_views.staff_home, name="staff_home"),
    path('staff_take_attendance/', staff_views.staff_take_attendance, name="staff_take_attendance"),
    path('get_students/', staff_views.get_students, name="get_students"),
    path('save_attendance_data/', staff_views.save_attendance_data, name="save_attendance_data"),
    path('staff_update_attendance/', staff_views.staff_update_attendance, name="staff_update_attendance"),
    path('get_attendance_dates/', staff_views.get_attendance_dates, name="get_attendance_dates"),
    path('get_attendance_student/', staff_views.get_attendance_student, name="get_attendance_student"),
    path('update_attendance_data/', staff_views.update_attendance_data, name="update_attendance_data"),
    path('staff_apply_leave/', staff_views.staff_apply_leave, name="staff_apply_leave"),
    path('staff_apply_leave_save/', staff_views.staff_apply_leave_save, name="staff_apply_leave_save"),
    path('staff_feedback/', staff_views.staff_feedback, name="staff_feedback"),
    path('staff_feedback_save/', staff_views.staff_feedback_save, name="staff_feedback_save"),
    path('staff_profile/', staff_views.staff_profile, name="staff_profile"),
    path('staff_profile_update/', staff_views.staff_profile_update, name="staff_profile_update"),
    path('staff_add_result/', staff_views.staff_add_result, name="staff_add_result"),
    path('staff_add_result_save/', staff_views.staff_add_result_save, name="staff_add_result_save"),

    # URSL for Student
    path('student_home/', student_views.student_home, name="student_home"),
    path('student_view_attendance/', student_views.student_view_attendance, name="student_view_attendance"),
    path('student_view_attendance_post/', student_views.student_view_attendance_post,
         name="student_view_attendance_post"),
    path('student_apply_leave/', student_views.student_apply_leave, name="student_apply_leave"),
    path('student_apply_leave_save/', student_views.student_apply_leave_save, name="student_apply_leave_save"),
    path('student_feedback/', student_views.student_feedback, name="student_feedback"),
    path('student_feedback_save/', student_views.student_feedback_save, name="student_feedback_save"),
    path('student_profile/', student_views.student_profile, name="student_profile"),
    path('student_profile_update/', student_views.student_profile_update, name="student_profile_update"),
    path('student_view_result/', student_views.student_view_result, name="student_view_result"),
]

st_martins/pores_portal/forms.py
from django import forms
from django.forms import Form
from .models import Courses, SessionYearModel


class DateInput(forms.DateInput):
    input_type = "date"


class AddStudentForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=50, widget=forms.EmailInput(attrs={"class": "form-control"}))
    password = forms.CharField(label="Password", max_length=50,
                               widget=forms.PasswordInput(attrs={"class": "form-control"}))
    first_name = forms.CharField(label="First Name", max_length=50,
                                 widget=forms.TextInput(attrs={"class": "form-control"}))
    last_name = forms.CharField(label="Last Name", max_length=50,
                                widget=forms.TextInput(attrs={"class": "form-control"}))
    username = forms.CharField(label="Username", max_length=50, widget=forms.TextInput(attrs={"class": "form-control"}))
    address = forms.CharField(label="Address", max_length=50, widget=forms.TextInput(attrs={"class": "form-control"}))

    # For Displaying Courses
    try:
        courses = Courses.objects.all()
        course_list = []
        for course in courses:
            single_course = (course.id, course.course_name)
            course_list.append(single_course)
    except:
        course_list = []

    # For Displaying Session Years
    try:
        session_years = SessionYearModel.objects.all()
        session_year_list = []
        for session_year in session_years:
            single_session_year = (
            session_year.id, str(session_year.session_start_year) + " to " + str(session_year.session_end_year))
            session_year_list.append(single_session_year)

    except:
        session_year_list = []

    gender_list = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )

    course_id = forms.ChoiceField(label="Course", choices=course_list,
                                  widget=forms.Select(attrs={"class": "form-control"}))
    gender = forms.ChoiceField(label="Gender", choices=gender_list,
                               widget=forms.Select(attrs={"class": "form-control"}))
    session_year_id = forms.ChoiceField(label="Session Year", choices=session_year_list,
                                        widget=forms.Select(attrs={"class": "form-control"}))
    # session_start_year = forms.DateField(label="Session Start", widget=DateInput(attrs={"class":"form-control"}))
    # session_end_year = forms.DateField(label="Session End", widget=DateInput(attrs={"class":"form-control"}))
    profile_pic = forms.FileField(label="Profile Pic", required=False,
                                  widget=forms.FileInput(attrs={"class": "form-control"}))


class EditStudentForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=50, widget=forms.EmailInput(attrs={"class": "form-control"}))
    first_name = forms.CharField(label="First Name", max_length=50,
                                 widget=forms.TextInput(attrs={"class": "form-control"}))
    last_name = forms.CharField(label="Last Name", max_length=50,
                                widget=forms.TextInput(attrs={"class": "form-control"}))
    username = forms.CharField(label="Username", max_length=50, widget=forms.TextInput(attrs={"class": "form-control"}))
    address = forms.CharField(label="Address", max_length=50, widget=forms.TextInput(attrs={"class": "form-control"}))

    # For Displaying Courses
    try:
        courses = Courses.objects.all()
        course_list = []
        for course in courses:
            single_course = (course.id, course.course_name)
            course_list.append(single_course)
    except:
        course_list = []

    # For Displaying Session Years
    try:
        session_years = SessionYearModel.objects.all()
        session_year_list = []
        for session_year in session_years:
            single_session_year = (
            session_year.id, str(session_year.session_start_year) + " to " + str(session_year.session_end_year))
            session_year_list.append(single_session_year)

    except:
        session_year_list = []

    gender_list = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )

    course_id = forms.ChoiceField(label="Course", choices=course_list,
                                  widget=forms.Select(attrs={"class": "form-control"}))
    gender = forms.ChoiceField(label="Gender", choices=gender_list,
                               widget=forms.Select(attrs={"class": "form-control"}))
    session_year_id = forms.ChoiceField(label="Session Year", choices=session_year_list,
                                        widget=forms.Select(attrs={"class": "form-control"}))
    # session_start_year = forms.DateField(label="Session Start", widget=DateInput(attrs={"class":"form-control"}))
    # session_end_year = forms.DateField(label="Session End", widget=DateInput(attrs={"class":"form-control"}))
    profile_pic = forms.FileField(label="Profile Pic", required=False,
                                  widget=forms.FileInput(attrs={"class": "form-control"}))

st_martins/pores_portal/views.py
# from channels.auth import login, logout
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages

from .email_backend import EmailBackEnd


def home(request):
    return render(request, 'pores_portal/index.html')


def loginPage(request):
    return render(request, 'pores_portal/login.html')


def doLogin(request):
    if request.method != "POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        user = EmailBackEnd.authenticate(request, username=request.POST.get('email'),
                                         password=request.POST.get('password'))
        if user != None:
            login(request, user)
            user_type = user.user_type
            # return HttpResponse("Email: "+request.POST.get('email')+ " Password: "+request.POST.get('password'))
            if user_type == '1':
                return redirect('pores_portal:admin_home')

            elif user_type == '2':
                # return HttpResponse("Staff Login")
                return redirect('pores_portal:staff_home')

            elif user_type == '3':
                # return HttpResponse("Student Login")
                return redirect('pores_portal:student_home')
            else:
                messages.error(request, "Invalid Login!")
                return redirect('login')
        else:
            messages.error(request, "Invalid Login Credentials!")
            # return HttpResponseRedirect("/")
            return redirect('login')


def get_user_details(request):
    if request.user != None:
        return HttpResponse("User: " + request.user.email + " User Type: " + request.user.user_type)
    else:
        return HttpResponse("Please Login First")


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')

st_martins/pores_portal/templates/pores_portal/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>School Management System | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'pores_portal/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'pores_portal/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'pores_portal/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'pores_portal/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'pores_portal/dist/css/adminlte.min.css'  %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'pores_portal/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'pores_portal/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'pores_portalsummernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


</head>



{% block content %}


{% endblock %}
{% include 'pores_portal/staff_template/footer.html' %}

<!-- jQuery -->
<script src="{% static 'pores_portal/jquery/jquery.min.js'  %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'pores_portal/jquery-ui/jquery-ui.min.js'  %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'pores_portal/bootstrap/js/bootstrap.bundle.min.js'  %}"></script>
<!-- ChartJS -->
<script src="{% static 'pores_portal/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'pores_portal/sparklines/sparkline.js'  %}"></script>
<!-- JQVMap -->
<script src="{% static 'pores_portal/jqvmap/jquery.vmap.min.js'  %}"></script>
<script src="{% static 'pores_portal/jqvmap/maps/jquery.vmap.usa.js'  %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'pores_portal/jquery-knob/jquery.knob.min.js'  %}"></script>
<!-- daterangepicker -->
<script src="{% static 'pores_portal/moment/moment.min.js'  %}"></script>
<script src="{% static 'pores_portal/daterangepicker/daterangepicker.js'  %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'pores_portal/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'  %}"></script>
<!-- Summernote -->
<script src="{% static 'pores_portal/summernote/summernote-bs4.min.js'  %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'pores_portal/overlayScrollbars/js/jquery.overlayScrollbars.min.js'  %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'pores_portal/dist/js/adminlte.js'  %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'pores_portal/dist/js/pages/dashboard.js'  %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'pores_portal/dist/js/demo.js'  %}"></script>
</body>
</html>

st_martins/pores_portal/templates/pores_portal/footer.html
<footer class="main-footer">
      <strong>Copyright &copy; {% now "Y" %}, <a href="https://www.stmartdepores.com">Depores Team</a>.</strong>
      All rights reserved.
      <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0
      </div>
    </footer>

st_martins/pores_portal/templates/pores_portal/login.html
{% extends 'pores_portal/base.html' %}
{% load static %} 


{% block content %}

<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{% url 'pores_portal:login' %}"><b>ST MARTINS DEPORES</b> SCHOOL</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in </p>

      <form action="{% url 'pores_portal:doLogin' %}" method="POST">
      {% csrf_token %}
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="Email" name="email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>

          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>

          {% comment %} <div class="col-12 text-center">
            <a href="{% url 'pores_portal:password_reset' %}">Reset Password</a>
          </div>  {% endcomment %}

          {% comment %} Display Messages {% endcomment %}
          {% if messages %}
          <div class="col-12">
            {% for message in messages %}
              {% if message.tags == "error" %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endif %}
            {% endfor %}
          </div>
          {% endif %}
      </form>

</div>
  </div>
</div>
</body>
<!-- /.login-box -->

{% endblock %}